name: face_recognition_web
description: "Wtb interface for face recognition server."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7+1

  mime: ^1.0.0
  http: ^1.2.2
  http_parser: ^4.0.0
  file_picker: ^10.1.2

  image_cropper: ^9.0.0
  image_picker_for_web: ^3.0.6
  image: ^4.5.4
  photo_view: ^0.15.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
